# -*- coding: utf-8 -*-
"""Binary tree.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lsTbLD873_sz2IXAsFi0-G5kru0_VuxE
"""

class Node:
    def __init__(self,data):
        self.data=data
        self.left=None
        self.right=None

def Insert(node,data):
        if node is None:   
            return Node(data)

        if data < node.data:
            node.left=Insert(node.left,data)
        else:
            node.right=Insert(node.right,data)       
        return node
           
def Print_tree(node):
        if node is None:
            return
        
        print(node.data)
        Print_tree(node.left)
        Print_tree(node.right)

if __name__=="__main__":
   tree=None
   tree=Insert(tree,10)
   tree=Insert(tree,5)
   tree=Insert(tree,15)
   tree=Insert(tree,12)
   tree=Insert(tree,17)
   tree=Insert(tree,7)
   tree=Insert(tree,3)
   Print_tree(tree)